title = "Development Configuration"

[connection]
  ip = "localhost"
  port = "8081"

[window]
  width = 800
  height = 600
  vsync = false
  fullscreen = false

[settings]
  SoundVolume = 0.5
  MusicVolume = 0.5

[controls]
  left = 65
  right = 68
  up = 87
  down = 83
  menu = 258

[playerdata]
  username = "Damien"